version: '3.4'

services:
  influxdb:
    container_name: influxdb
    image: bitnami/influxdb:1.8.5-debian-10-r264
    environment:
      - INFLUXDB_ADMIN_USER=if_user
      - INFLUXDB_ADMIN_USER_PASSWORD=if_password
    ports:
      - "38086:8086"
    volumes:
      - ./influxdb/init_scripts:/docker-entrypoint-initdb.d
    networks:
      kasa_primary_network:
        ipv4_address: 10.10.177.10

  chronograf:
    container_name: chronograf
    image: chronograf:1.9.4
    ports:
      - '38888:8888'
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=if_user
      - INFLUXDB_PASSWORD=if_password
    networks:
      kasa_primary_network:
        ipv4_address: 10.10.177.20

  grafana:
    container_name: grafana
    image: localdev/grafana:latest
    ports:
      - '33000:3000'
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=gf
      - GF_SECURITY_ADMIN_PASSWORD=gfp
    volumes:
      - ./grafana:/etc/grafana/provisioning
    networks:
      kasa_primary_network:
        ipv4_address: 10.10.177.30

networks:
  kasa_primary_network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.177.0/24
