#!/bin/bash -x

export INFLUX_COMMAND="influx -username ${INFLUXDB_ADMIN_USER} -password ${INFLUXDB_ADMIN_USER_PASSWORD}"

$INFLUX_COMMAND -execute 'SHOW DATABASES'
$INFLUX_COMMAND -execute 'CREATE DATABASE _internal'
$INFLUX_COMMAND -execute 'CREATE DATABASE kasa'
$INFLUX_COMMAND -execute 'SHOW DATABASES'
