{
 "title": "Power Usage 1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kdb_interval",
    "query": "5s,10s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Mac Mini Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L3 Mac Mini" }
     ]
    }
   ]
  },
  {
   "title": "Mac Mini Monitor Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L1 Left Thunderbolt Monitor" }
     ]
    }
   ]
  },
  {
   "title": "MacBook Pro Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L4 MacBook Pro Dock" }
     ]
    }
   ]
  },
  {
   "title": "MacBook Pro Monitor Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L2 Right Thunderbolt Monitor " }
     ]
    }
   ]
  },
  {
   "title": "Home Computer Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "R1 Home Computer" }
     ]
    }
   ]
  },
  {
   "title": "Home Monitor Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "R3 Left Home Computer Monitor" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R4 Right Home Computer Monitor" }
     ]
    }
   ]
  },
  {
   "title": "Home Monitor Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "R3 Left Home Computer Monitor" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R4 Right Home Computer Monitor" }
     ]
    }
   ]
  },
  {
   "title": "Charger Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L5 Pixel Stand" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L6 Watch" }
     ]
    }
   ]
  },
  {
   "title": "Total Desk Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "Left Office Desk Strip" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "Right Office Desk Strip" }
     ]
    }
   ]
  },
  {
   "title": "Mac Mini Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L3 Mac Mini" }
     ]
    }
   ]
  },
  {
   "title": "MacBook Pro Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L4 MacBook Pro Dock" }
     ]
    }
   ]
  },
  {
   "title": "Home Computer Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "R1 Home Computer" }
     ]
    }
   ]
  },
  {
   "title": "Charger Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L5 Pixel Stand" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L6 Watch" }
     ]
    }
   ]
  },
  {
   "title": "Strip Power Usage by Power Strip (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sample_level", "operator": "=", "value": "strip" }
     ]
    }
   ]
  },
  {
   "title": "Plug Power Usage by Plug (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sample_level", "operator": "=", "value": "plug" }
     ]
    }
   ]
  },
  {
   "title": "Strip Power Usage Stacked by Power Strip (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sample_level", "operator": "=", "value": "strip" }
     ]
    }
   ]
  },
  {
   "title": "Monitor Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L1 Left Thunderbolt Monitor" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "L2 Right Thunderbolt Monitor " },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R3 Left Home Computer Monitor" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R4 Right Home Computer Monitor" }
     ]
    }
   ]
  },
  {
   "title": "Home Computer Monitor Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "R3 Left Home Computer Monitor" }
     ]
    }
   ]
  },
  {
   "title": "Plug Power Usage Stacked by Plug (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sample_level", "operator": "=", "value": "plug" }
     ]
    }
   ]
  },
  {
   "title": "Computer Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "query": "SELECT mean(\"value\") FROM \"current_power_usage\" WHERE (\"alias\" = 'L3 Mac Mini' OR \"alias\" = 'L4 MacBook Pro Dock' OR \"alias\" = 'R1 Home Computer') AND $timeFilter GROUP BY time($kdb_interval), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "L3 Mac Mini" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "L4 MacBook Pro Dock" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R1 Home Computer" },
      { "condition": "OR", "key": "alias", "operator": "=", "value": "R4 Right Home Computer Monitor" }
     ]
    }
   ]
  },
  {
   "title": "Plug Current State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sample_level", "operator": "=", "value": "plug" }
     ]
    }
   ]
  },
  {
   "title": "Exercise Bike Strip Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "Exercise Bike Strip" }
     ]
    }
   ]
  },
  {
   "title": "Basement TV Strip Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$kdb_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "Basement TV" }
     ]
    }
   ]
  }
 ]
}