apiVersion: 1

deleteDatasources:
  - name: MYINFLUX
    orgId: 1

datasources:
  - name: MYINFLUXDB
    type: influxdb
    access: proxy
    url: https://influxdb
    password: if
    user: ifp
    database: kasa
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true
