apiVersion: 1

deleteDatasources:
  - name: influxdb1
    orgId: 1

datasources:
  - name: influxdb1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: if_user
    database: kasa
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      httpMode: GET
    secureJsonData:
      password: if_password
    version: 1
    editable: true
