apiVersion: 1

deleteDatasources:
  - name: influxdb1
    orgId: 1

datasources:
  - name: influxdb1
    type: influxdb
    access: proxy
    url: $INFLUXDB_URL
    user: $INFLUXDB_USERNAME
    database: kasa
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUXDB_PASSWORD
    version: 1
    editable: true
